Feature/module4 home work
liushnya/goFrontEndHomework pull request #5
Opened 2021-06-27 15:24 UTC by liushnya

2021-06-27 17:30 UTC, MrNightingale requested changes
1) change nav links colors
2) near links with submenu there should be a triangle. Create triangle using css

2021-06-27 17:30 UTC, MrNightingale commented on mod4hw/css/style.css
> +    height: 95%;
redundant

2021-06-27 17:30 UTC, MrNightingale commented on mod4hw/css/style.css
> +    width: 1002px;
no need to set it for every section since you've got `content` class for that

2021-06-27 17:30 UTC, MrNightingale commented on mod4hw/css/style.css
> +.content {
better name is `content-wrapper`

2021-06-27 17:30 UTC, MrNightingale commented on mod4hw/css/style.css
> +    width: 1000px;
max-width

2021-06-27 17:30 UTC, MrNightingale commented on mod4hw/css/style.css
> +    margin: 0;
`margin: 0 auto`

2021-06-27 17:30 UTC, MrNightingale commented on mod4hw/index.html
> +            <div class="empty-space">
works without it

2021-06-27 17:30 UTC, MrNightingale commented on mod4hw/css/style.css
> +    box-shadow: 0px 7px 14px -2px #000000;
#000000 -> #000

2021-06-27 17:33 UTC, MrNightingale commented on mod4hw/css/style.css
> +.text {
add white bg color since when you've got a lot of text in a sidebars bg color is missing

2021-06-29 18:16 UTC, liushnya commented on mod4hw/index.html
> +            <div class="empty-space">
it doesn't :(

2021-06-29 19:54 UTC, MrNightingale commented
@liushnya add general `section wrapper` as we discussed. no need to add width and margin auto for every section

2021-07-06 07:06 UTC, merged

2021-07-06 08:20 UTC, MrNightingale requested changes
fix comments and review fb btn implementation